name: Deploy Admin Panel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./admin
        run: npm install

      - name: Build the project
        working-directory: ./admin
        run: npm run build

      - name: Deploy to Cloudflare Pages
        working-directory: ./admin
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PROJECT_NAME: gigworks-admin
        run: |
          npm install -g @cloudflare/wrangler
          npm run deploy

      - name: Notify success
        run: echo "Deployment successful"